#!/usr/bin/env bash

export KUBERNETES_VERSION=1.10.3
export VAGRANT_VERSION=2.2.3
export GRADLE_VERSION=5.2.1
export JAVA_VERSION=8
export GOLANG_VERSION=1.12.1
export DOCKER_COMPOSE_VERSION=1.23.2
export DOCKER_MACHINE_VERSION=0.16.0
