#!/usr/bin/env bash

export KUBERNETES_VERSION=1.10.3
export VAGRANT_VERSION=2.1.1
export GRADLE_VERSION=4.8
export JAVA_VERSION=8
export GOLANG_VERSION=1.10.2
export DOCKER_COMPOSE_VERSION=1.21.2
export DOCKER_MACHINE_VERSION=0.14.0

